---
# Provisioning per vagrant.
- name: Verifico versione server - NethServer
  shell: /sbin/e-smith/db configuration getprop sysconfig ProductName
  register: chk_nethserver
  ignore_errors: yes
  sudo: yes

- name: Configuro la scheda secondaria
  shell: /sbin/e-smith/db networks setprop eth1 bootproto none device eth1 ipaddr 192.168.1.1 netmask 255.255.255.0 onboot yes role green
  when: "'NethServer' in chk_nethserver.stdout"
  sudo: yes
  notify:
    - interface update

- name: Aggiungo utente per compilazione pacchetti RPM
  user:
    name: makepkg
    password: $6$rounds=100000$neTGJ5N7Nu5ogCTX$VmVgS9HRZcdczjiNNdQcZzFVQI/3AFwu6MNFOKxGhBRY4VcBOo6GTxhXr0K/jYVFTygjHWsr.teM6RmBzSnz.0
    shell: /bin/bash
    state: present
  sudo: yes

- name: Preparazione pacchetti per compilazione RPM
  yum: pkg="{{ item }}" state=present
  with_items:
    - '@Development tools'
    - libselinux-python
    - rpmdevtools
    - yum-utils
    - rpmlint
  sudo: yes

- name: Copia della chiave pubblica
  authorized_key: 
    user: makepkg
    key: "{{ lookup('file', '/Users/syntaxerrormmm/.ssh/id_rsa.pub') }}"
    state: present
  sudo: yes

- name: Creazione directory per il build di RPM
  shell: rpmdev-setuptree
  sudo: yes
  sudo_user: makepkg
