---
- name: Verifico la presenza del gruppo Domain Users
  shell: /sbin/e-smith/db accounts show domusers
  register: check_domusers
  sudo: yes
  ignore_errors: true

- name: Creazione gruppo Domain Users
  shell: /sbin/e-smith/db accounts set domusers group Description "Domain Users" Members admin Removable no
  sudo: yes
  when: check_domusers|failed

- name: Configurazione nuovo gruppo Domain Users
  shell: /sbin/e-smith/signal-event group-create domusers
  sudo: yes
  when: check_domusers|failed

- name: Verifico la presenza del gruppo Domain Operators
  shell: /sbin/e-smith/db accounts show domopers
  register: check_domopers
  sudo: yes
  ignore_errors: true

- name: Creazione gruppo Domain Operators
  shell: /sbin/e-smith/db accounts set domopers group Description "Domain Operators" Removable no
  sudo: yes
  when: check_domopers|failed

- name: Configurazione nuovo gruppo Domain Operators
  shell: /sbin/e-smith/signal-event group-create domopers
  sudo: yes
  when: check_domopers|failed

- name: Verifico la presenza del gruppo Docenti
  shell: /sbin/e-smith/db accounts show docenti
  register: check_docenti
  sudo: yes
  ignore_errors: true

- name: Creazione gruppo Docenti
  shell: /sbin/e-smith/db accounts set docenti group Description "Docenti" Removable no
  sudo: yes
  when: check_docenti|failed

- name: Configurazione nuovo gruppo Docenti
  shell: /sbin/e-smith/signal-event group-create docenti
  sudo: yes
  when: check_docenti|failed

