---
# Configurazione principale di NethServer.

# Installo pacchetti addizionali
- include: neth_pkgs.yml
  tags:
    - nethpkg

- include: reconfig_nic.yml
  when: ansible_product_name == "VirtualBox"
  tags:
    - nethnic

- include: reconfig_srv.yml
  tags:
    - nethcfg
