---
# Configurazione principale di NethServer.

# Installo pacchetti addizionali
- include: neth_pkgs.yml

- include: reconfig_nic.yml
  when: ansible_product_name == "VirtualBox"

- include: reconfig_srv.yml
