---
# Configurazione principale di NethServer.

# Installo pacchetti addizionali
- include: neth_pkgs.yml
  tags:
    - nethpkg

- include: reconfig_nic.yml
  tags:
    - nethnic

- include: reconfig_srv.yml
  tags:
    - nethcfg

- include: domain_groups.yml
  tags:
    - domaingroups
