---
addin_pkgs:
  - git
  - vim-enhanced
  - screen
  - sshpass
  - ansible

neth_pkgs:
  - nethserver-tftp
  - nethserver-ibays
  - nethserver-samba
  - nethserver-samba-audit
  - nethserver-cups
  - nethserver-avahi
  - nethserver-dnsmasq
  - nethserver-collectd
  - nethserver-collectd-web
  - nethserver-squid
  - nethserver-squidclamav
  - nethserver-squidguard
  - nethserver-firewall-base
