---

- name: Configuring executive mirrorpath
  set_fact:
    execmirrorpath: "{{ ansible_local.domain.mirrorpath }}"
  when: ansible_local.domain.mirror_mode == 'local' or ansible_local.domain.mirror_mode == 'nfs'

- include: local-mirror.yml
  when: ansible_local.domain.mirror_mode == 'local'
  tags:
    - mirror
    - local-mirror

- include: nfs-mirror.yml
  when: ansible_local.domain.mirror_mode == 'nfs'
  become: yes
  tags:
    - mirror
    - nfs-mirror

- include: remote-mirror.yml
  when: ansible_local.domain.mirror_mode == 'remote'
  become: yes
  tags:
    - mirror
    - remote-mirror
