---

- name: Verifica installazione git 
  yum: name=git state=present
  become: yes
  tags: git

- name: Verifica installazione ansible 
  yum: name=ansible state=present
  become: yes
  tags: ansible

- name: Installazione python-argparse
  shell:
    name: "ftp://fr2.rpmfind.net/linux/centos/6.7/extras/i386/Packages/python-argparse-1.2.1-2.el6.centos.noarch.rpm"
    state: present
  become: yes
  tags: ansible

  #- name: Download della gestione client con ansible
  #  git:
  #    repo: "https://github.com/bglug-it/ps-clientmgmt.git"
  #    dest: /home/amgmt/clientmgmt
  #  tags:
  #    - git
  #    - ansible
  #
  #- name: Attivo sotto modulo ansdyninv
  #  shell: cd /home/amgmt/clientmgmt/ansdyninv; git submodule init && git submodule update
  #  tags:
  #    - git
  #    - ansible
