---

- name: Verifica installazione pacchetti aggiuntivi
  shell: rpm -q {{ item }}
  sudo: yes
  with_items: addins_pkg 
  register: check_pkg
  changed_when: check_pkg.rc != 0
  tags: pkg

- name: Verifica configurazione CentOS 6
  file: name=/etc/yum.repos.d/{{ item }} state=file
  sudo: yes
  with_items: centos_repo_files
  when: check_pkg|changed
  register: check_repos
  tags: repo

- name: Scarico configurazione per CentOS 6
  get_url:
    url: http://mirror.centos.org/centos/6/os/x86_64/Packages/centos-release-6-6.el6.centos.12.2.x86_64.rpm
    dest: /tmp/centos-release-6-6.el6.centos.12.2.x86_64.rpm
  sudo: yes
  when: check_repos|failed
  tags: repo

- name: Scompatto configurazione CentOS 6
  shell: mkdir -p /tmp/centos-release && pushd /tmp/centos-release && rpm2cpio ../centos-release-6-6.el6.centos.12.2.x86_64.rpm | cpio -idmv && popd
  sudo: yes
  when: check_repos|failed
  tags: repo

- name: Copio i repository
  shell: cp -f /tmp/centos-release/etc/yum.repos.d/{{ item }} /etc/yum.repos.d/
  with_items: centos_repo_files
  sudo: yes
  when: check_repos|failed
  register: centos_repo_installed
  tags: repo

- name: Copio le chiavi di firma GPG
  shell: cp -f /tmp/centos-release/etc/pki/rpm-gpg/{{ item }} /etc/pki/rpm-gpg/
  with_items: centos_gpg_files
  sudo: yes
  when: check_repos|failed
  tags: repo

  # Senza di questa, non è possibile installare EPEL dopo
- name: Prima attivazione repo
  shell: yum clean all && yum repolist
  sudo: yes
  register: first_repo_activate
  when: centos_repo_installed|changed
  async: 600
  poll: 10
  tags: repo

- name: Attivo EPEL
  yum: name=epel-release state=present
  sudo: yes
  when: first_repo_activate|changed
  register: epel_installed
  tags: repo

- name: Seconda attivazione repo
  shell: yum clean all && yum repolist
  sudo: yes
  when: epel_installed|changed
  async: 600
  poll: 10
  tags: repo

- name: Pulizia
  shell: rm -rf /tmp/centos-release && rm -f /tmp/centos-release-6-6.el6.centos.12.2.x86_64.rpm /tmp/epel-release-6-8.noarch.rpm
  sudo: yes
  when: check_repos|failed
  tags: repo

- name: Installo pacchetti di gestione
  yum: name={{ item }} state=present
  sudo: yes
  when: ansible_os_family == 'ClearOS'
  with_items: addin_pkgs
  async: 3600
  poll: 30
  tags: pkg
