---

- name: Rimozione repository centrali CentOS 6
  shell: rm -f /etc/yum.repos.d/{{ item }}
  with_items: centos_repo_files
  sudo: yes
    
- name: Rimozione firme GPG repository CentOS 6
  shell: rm -f /etc/pki/rpm-gpg/{{ item }}
  with_items: centos_gpg_files
  sudo: yes

- name: Ripristino repository ad originali
  shell: yum clean all && yum repolist
  sudo: yes
