---

- include: ssh-keygen.yml
  tags: ssh

- include: centos_pkgs.yml
  when: ansible_distribution == "CentOS" and ansible_os_family == "RedHat"
  tags: centos

- include: ansible.yml
  when: ansible_distribution == "CentOS"
  tags:
    - git
    - ansible

- include: neth_pkgs.yml
  when: ansible_distribution == "CentOS" and ansible_os_family == "RedHat"
  tags: neth
