---

- include: ssh-keygen.yml
  tags: ssh

- include: lock-nethrelease.yml
  sudo: yes
  tags: lock-nethrelease

- include: centos_pkgs.yml
  when: ansible_distribution == "CentOS" and ansible_os_family == "RedHat"
  tags: centos

- include: pvtrepo.yml
  tags: sys42.eu

- include: ansible.yml
  when: ansible_distribution == "CentOS"
  tags:
    - git
    - ansible
