---
# Configurazioni a quanto pare non fattibili dall'interfaccia
- name: Configuro il servizio DNS come resolver
  shell: /sbin/e-smith/db configuration setprop dns role resolver NameServers 208.67.222.222,208.67.220.220 
  sudo: yes
  tags: dns

- name: Configuro sincronizzazione dell'ora con NTP1
  shell: /sbin/e-smith/db configuration setprop ntpd NTPServer ntp1.inrim.it status enabled && /sbin/e-smith/signal-event nethserver-ntp-save
  sudo: yes
  tags: ntp
