---
# Configurazioni a quanto pare non fattibili dall'interfaccia
- name: Configuro il servizio DNS come resolver
  shell: /sbin/e-smith/db configuration setprop dns role resolver NameServers 208.67.222.222,208.67.220.220 
  sudo: yes
  tags: dns

- name: Configuro sincronizzazione dell'ora con NTP1
  shell: /sbin/e-smith/db configuration setprop ntpd NTPServer ntp1.inrim.it status enabled
  sudo: yes
  notify:
    - ntp save
  tags: ntp

- name: Lancio aggiornamenti del clamav
  shell: /sbin/e-smith/signal-event nethserver-squidclamav-update
  sudo: yes
  tags: clamav

- name: Verifico la presenza del gruppo
  shell: /sbin/e-smith/db accounts show domusers
  sudo: yes
  tags: groups
  register: check_domusers
  ignore_errors: yes

- name: Aggiungo gruppo "Domain users"
  shell: /sbin/e-smith/db accounts set domusers group && /sbin/e-smith/db accounts setprop domusers Description 'Domain Users' Gid 502 Members admin Removable no
  sudo: yes
  tags: groups
  notify:
    - group create
  when: check_domusers|failed
