---
- name: Installazione istruzioni per repo sys42.eu
  copy:
    src: sys42.repo
    dest: /etc/yum.repos.d/sys42.repo
  become: yes

- name: Ricalcolo repository disponibili
  shell: yum repolist
  become: yes
